export const projects = [
  {
    id: 14,
    slug: "sidata",
    title: "SIDATA - Sistem Informasi Data Keluarga Tangsel",
    description: "Aplikasi web untuk pengelolaan data keluarga, statistik kependudukan, dan layanan permohonan data di Kota Tangerang Selatan.",
    thumbnail: "/projects/sidata/thumb.png",
    screenshots: ["/projects/sidata/1.png", "/projects/sidata/2.png", "/projects/sidata/3.png", "/projects/sidata/4.png", "/projects/sidata/5.png", "/projects/sidata/6.png", "/projects/sidata/7.png", "/projects/sidata/8.png", "/projects/sidata/9.png"],
    link: "https://sidata.tangsel.go.id",
    tags: ["React.js", "Tailwind CSS", "Typescript", "Express.js", "MySQL"],
    category: "Sistem Informasi",
    status: "Completed",
    created: "2024-05-01",
    updated: "2024-06-01",
    contributors: 3,
    views: 2345,
    progress: 100,
    funFact: "SIDATA membantu pemerintah Tangsel dalam pengambilan keputusan berbasis data.",
    features: [
      "Manajemen data keluarga",
      "Statistik kependudukan real-time",
      "Permohonan data online",
      "Dashboard interaktif",
      "Export data ke Excel/PDF"
    ],
  },
  {
    id: 13,
    slug: "garmen",
    title: "GarmenTrack - Sistem Tracking & Inventori Pabrik Garmen",
    description: "Platform untuk memonitor proses produksi, stok bahan baku, dan pengiriman barang di pabrik garmen/tekstil.",
    thumbnail: "/projects/garmen/thumb.png",
    screenshots: ["/projects/garmen/1.png", "/projects/garmen/2.png", "/projects/garmen/3.png", "/projects/garmen/4.png", "/projects/garmen/5.png", "/projects/garmen/6.png", "/projects/garmen/7.png"],
    link: "https://garmen-track.com",
    tags: ["Laravel", "Tailwind CSS", "Postgres"],
    category: "Sistem Informasi",
    status: "Completed",
    created: "2024-03-15",
    updated: "2024-05-20",
    contributors: 2,
    views: 1890,
    progress: 100,
    funFact: "Sistem ini mengurangi kehilangan stok hingga 30% di tahun pertama implementasi.",
    features: [
      "Tracking proses produksi",
      "Manajemen stok bahan baku",
      "Laporan pengiriman barang",
      "Notifikasi otomatis",
      "Multi-user role"
    ],
  },
  {
    id: 12,
    slug: "forumkm",
    title: "ForUMKM - Platform Layanan UMKM",
    description: "Aplikasi web untuk membantu pelaku UMKM mempromosikan produk, mencari mitra, dan mengakses pelatihan bisnis.",
    thumbnail: "/projects/forumkm/thumb.png",
    screenshots: ["/projects/forumkm/1.png", "/projects/forumkm/2.png", "/projects/forumkm/3.png", "/projects/forumkm/4.png"],
    link: "https://forumkm.id",
    tags: ["Next.js", "Tailwind CSS", "Typescript"],
    category: "Web App",
    status: "Completed",
    created: "2023-12-01",
    updated: "2024-01-10",
    contributors: 4,
    views: 3200,
    progress: 100,
    funFact: "Lebih dari 500 UMKM telah bergabung dalam 3 bulan pertama.",
    features: [
      "Marketplace produk UMKM",
      "Forum diskusi & konsultasi",
      "Pelatihan online",
      "Dashboard analytics",
      "Integrasi pembayaran"
    ],
  },
  {
    id: 11,
    slug: "darunnajah",
    title: "SIAKAD - Sistem Informasi Akademik Darunnajah",
    description: "Sistem informasi akademik untuk pengelolaan data santri, nilai, absensi, dan jadwal di Pesantren Darunnajah.",
    thumbnail: "/projects/darunnajah/thumb.png",
    screenshots: ["/projects/darunnajah/1.png", "/projects/darunnajah/2.png", "/projects/darunnajah/3.png", "/projects/darunnajah/4.png"],
    link: "https://siakad.darunnajah.sch.id",
    tags: ["Angular", "Bootstrap", "Typescript", "Postgres"],
    category: "Sistem Informasi",
    status: "Completed",
    created: "2023-08-01",
    updated: "2023-12-15",
    contributors: 2,
    views: 2100,
    progress: 100,
    funFact: "SIAKAD memudahkan wali santri memantau perkembangan anak secara online.",
    features: [
      "Manajemen data santri",
      "Input & rekap nilai",
      "Absensi online",
      "Cetak rapor digital",
      "Notifikasi jadwal"
    ],
  },
  {
    id: 10,
    slug: "noir",
    title: "Noir - Social Media App",
    description: "Aplikasi media sosial modern dengan fitur posting, komentar, dan dark mode.",
    thumbnail: "/projects/noir/thumb.png",
    screenshots: ["/projects/noir/1.png", "/projects/noir/2.png", "/projects/noir/3.png", "/projects/noir/4.png", "/projects/noir/5.png", "/projects/noir/6.png"],
    link: "https://noir-app.com",
    tags: ["Next.js", "Tailwind CSS", "Javascript", "Strapi"],
    category: "Web App",
    status: "Completed",
    created: "2023-10-10",
    updated: "2024-01-05",
    contributors: 3,
    views: 4100,
    progress: 100,
    funFact: "Noir punya fitur auto dark mode berdasarkan jam lokal user.",
    features: [
      "Posting & komentar",
      "Dark mode otomatis",
      "Realtime notification",
      "Profile customization",
      "Responsive UI"
    ],
  },
  {
    id: 1,
    slug: "ayovote",
    title: "Ayovote - Online Voting Platform",
    description: "Platform voting online untuk pemilihan organisasi, komunitas, dan event kampus secara aman dan transparan.",
    thumbnail: "/projects/ayovote/thumb.png",
    screenshots: ["/projects/ayovote/1.png", "/projects/ayovote/2.png", "/projects/ayovote/3.png", "/projects/ayovote/4.png"],
    link: "https://ayovote.com",
    tags: ["Next.js", "Tailwind CSS", "Typescript", "MongoDB"],
    category: "Web App",
    status: "Completed",
    created: "2023-09-01",
    updated: "2023-10-01",
    contributors: 2,
    views: 2800,
    progress: 100,
    funFact: "Digunakan oleh lebih dari 50 organisasi kampus di Indonesia.",
    features: [
      "Voting realtime",
      "Hasil transparan",
      "Multi-event support",
      "Notifikasi email",
      "Export hasil voting"
    ],
  },
  {
    id: 2,
    slug: "kelasku",
    title: "Kelasku - Mobile Learning App",
    description: "Aplikasi mobile untuk pembelajaran daring, diskusi kelas, dan pengumpulan tugas.",
    thumbnail: "/projects/kelasku/thumb.png",
    screenshots: ["/projects/kelasku/1.png", "/projects/kelasku/2.png", "/projects/kelasku/3.png", "/projects/kelasku/4.png", "/projects/kelasku/5.png", "/projects/kelasku/6.png", "/projects/kelasku/7.png", "/projects/kelasku/8.png"],
    link: "https://play.google.com/store/apps/details?id=com.kelasku.app",
    tags: ["React Native", "Expo", "Tailwind CSS"],
    category: "Mobile App",
    status: "Completed",
    created: "2023-07-01",
    updated: "2023-09-01",
    contributors: 3,
    views: 1500,
    progress: 100,
    funFact: "Fitur push notification-nya bikin siswa nggak pernah ketinggalan tugas!",
    features: [
      "Kelas online & diskusi",
      "Pengumpulan tugas",
      "Push notification",
      "Quiz interaktif",
      "Progress tracking"
    ],
  },
  {
    id: 3,
    slug: "monefy",
    title: "Monefy - Money Management Mobile App",
    description: "Aplikasi mobile untuk mencatat pemasukan, pengeluaran, dan budgeting harian.",
    thumbnail: "/projects/monefy/thumb.jpeg",
    screenshots: ["/projects/monefy/1.jpeg", "/projects/monefy/2.jpeg", "/projects/monefy/3.jpeg", "/projects/monefy/4.jpeg", "/projects/monefy/5.jpeg"],
    link: "https://play.google.com/store/apps/details?id=com.monefy.app",
    tags: ["React Native", "Firebase", "Tailwind CSS", "Expo"],
    category: "Mobile App",
    status: "Completed",
    created: "2023-06-01",
    updated: "2023-08-01",
    contributors: 2,
    views: 2100,
    progress: 100,
    funFact: "Lebih dari 10.000 download di bulan pertama rilis!",
    features: [
      "Catat pemasukan & pengeluaran",
      "Budgeting bulanan",
      "Grafik keuangan",
      "Sinkronisasi cloud",
      "Dark mode"
    ],
  },
  {
    id: 4,
    slug: "21cleanshoes",
    title: "21Cleanshoes - Laundry Sepatu Online",
    description: "Aplikasi web untuk pemesanan, tracking, dan pembayaran laundry sepatu secara online.",
    thumbnail: "/projects/21cleanshoes/thumb.png",
    screenshots: ["/projects/21cleanshoes/1.png", "/projects/21cleanshoes/2.png", "/projects/21cleanshoes/3.png", "/projects/21cleanshoes/4.png"],
    link: "https://21cleanshoes.com",
    tags: ["Next.js", "Tailwind CSS", "Typescript", "Framer Motion"],
    category: "Web App",
    status: "Completed",
    created: "2023-05-01",
    updated: "2023-06-01",
    contributors: 1,
    views: 900,
    progress: 100,
    funFact: "Pernah trending di Twitter lokal karena promo cuci gratis!",
    features: [
      "Pemesanan online",
      "Tracking status laundry",
      "Pembayaran digital",
      "Promo & diskon",
      "Notifikasi WhatsApp"
    ],
  },
];
