export const tagIconColorList = [
  { tag: 'React.js', icon: 'react', color: '#61DAFB' },
  { tag: 'React Native', icon: 'react', color: '#61DAFB' },
  { tag: 'Next.js', icon: 'nextjs', color: '#fff' },
  { tag: 'Typescript', icon: 'typescript', color: '#3178C6' },
  { tag: 'TypeScript', icon: 'typescript', color: '#3178C6' },
  { tag: 'Javascript', icon: 'javascript', color: '#F7DF1E' },
  { tag: 'Tailwind CSS', icon: 'tailwind', color: '#38BDF8' },
  { tag: 'Node.js', icon: 'nodejs', color: '#339933' },
  { tag: 'Express.js', icon: 'express', color: '#fff' },
  { tag: 'MongoDB', icon: 'mongodb', color: '#47A248' },
  { tag: 'MySQL', icon: 'mysql', color: '#4479A1' },
  { tag: 'Firebase', icon: 'firebase', color: '#FFCA28' },
  { tag: 'Expo', icon: 'expo', color: '#fff' },
  { tag: 'Framer Motion', icon: 'framer_motion', color: '#0055FF' },
  { tag: 'Figma', icon: 'figma', color: '#F24E1E' },
  { tag: 'Laravel', icon: 'laravel', color: '#FF2D20' },
  { tag: 'Supabase', icon: 'postgres', color: '#3ECF8E' },
  { tag: 'PostgreSQL', icon: 'postgres', color: '#336791' },
  { tag: 'Livewire', icon: 'laravel', color: '#4E5D94' },
  { tag: 'Bootstrap', icon: 'bootstrap', color: '#7952B3' },
  { tag: 'REST API', icon: 'nodejs', color: '#E535AB' },
  { tag: 'Socket.io', icon: 'nodejs', color: '#010101' },
  { tag: 'Strapi', icon: 'strapi', color: '#8A63D2' },
  { tag: 'Prisma', icon: 'prisma', color: '#2D3748' },
  { tag: 'Vue.js', icon: 'vue', color: '#42B883' },
  { tag: 'Angular', icon: 'angular', color: '#DD0031' },
  { tag: 'Postgres', icon: 'postgres', color: '#336791' },
  // New additions for Notu.AI and other projects
  { tag: 'WebSocket', icon: 'nodejs', color: '#010101' },
  { tag: 'Faster-Whisper', icon: 'sound', color: '#FF6B6B' },
  { tag: 'Playwright', icon: 'settings', color: '#45BA4B' },
  { tag: 'OpenRouter API', icon: 'settings', color: '#8B5CF6' },
  { tag: 'Git', icon: 'git', color: '#F05032' },
  { tag: 'GitHub', icon: 'github', color: '#fff' },
  { tag: 'Discord', icon: 'discord', color: '#5865F2' },
  { tag: 'Spotify', icon: 'spotify', color: '#1DB954' },
];
